# Generated by Django 6.0 on 2025-12-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_stock_close_price_stock_dividend_yield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity required for placing an order in this stock.'),
        ),
    ]
